update

diff --git a/motd b/motd
--- a/motd
+++ b/motd
@@ -10,7 +10,30 @@ let days=$((${upSeconds}/86400))
 UPTIME=`printf "%d days, %02dh%02dm%02ds" "$days" "$hours" "$mins" "$secs"`
 FREEMEM=$((`cat /proc/meminfo | grep MemFree | awk {'print $2'}`/1024))
 TOTMEM=$((`cat /proc/meminfo | grep MemTotal | awk {'print $2'}`/1024))
-IP=`/sbin/ifconfig eth0 | /bin/grep "inet addr" | /usr/bin/cut -d ":" -f 2 | /usr/bin/cut -d " " -f 1`
+#IP=`/sbin/ifconfig eth0 | /bin/grep "inet addr" | /usr/bin/cut -d ":" -f 2 | /usr/bin/cut -d " " -f 1`
+#if [[ -z "${IP}" ]]; then
+#  IP=`/sbin/ifconfig eth0 | /bin/grep "inet addr" | /usr/bin/cut -d ":" -f 2 | /usr/bin/cut -d " " -f 1`
+#fi
+#IP=""
+ifaces=("usb0" "eth0" "wlan0")
+for eth in "${ifaces[@]}"
+do
+#  IP=`/sbin/ifconfig ${eth} | /bin/grep "inet addr" | /usr/bin/cut -d ":" -f 2 | /usr/bin/cut -d " " -f 1`
+#  if [[ -z "${i}" ]]; then
+#    echo ""
+#  else
+#    break
+#  fi
+  IP=$(/sbin/ifconfig ${eth} | /bin/grep "inet addr" | /usr/bin/cut -d ":" -f 2 | /usr/bin/cut -d " " -f 1)
+  #if [[ $? ]]; then
+  if [[ ! -z "${IP}" ]]; then
+  #  echo "found ${eth}"
+    break
+  #else
+  #  echo "not found ${eth}"
+  fi
+done
+
 DF=`df -h | grep /dev/root | awk {'print $3 "B (Free) / " $2 "B (Total)"'}`
 CPUTEMP=$((`cat /sys/class/thermal/thermal_zone0/temp`/1000*9/5+32))
 
